export const SET_PRODUCTS = "SET_PRODUCTS"
export const SET_PRODUCTS_FAIL = "SET_PRODUCTS_FAIL"
export const SET_DETAIL_STATE = "SET_DETAIL_STATE"
export const SET_PRODUCT_FILTER = "SET_PRODUCT_FILTER"
export const GET_COLORS = "GET_COLORS";
export const GET_BRANDS = "GET_BRANDS";
export const SET_BRANDS_FAIL = "SET_BRANDS_FAIL"
export const SET_COLORS_FAIL = "SET_COLORS_FAIL"